import { ArrowRight, BookOpen, Brain, FileText, Library, ShieldCheck, Target } from 'lucide-react';
import { useEffect } from 'react';
import { Link } from 'wouter';
import { exams } from '@/data/exams';
import { Button, Card, Container, ExamCard, Layout, SectionTitle } from '@/components/site';

export default function Home() {
  useEffect(() => {
    document.title = 'ExamSetu4U - Free Exam Preparation Platform';
    const description = 'Free exam preparation platform for Indian students with study material, previous year questions, MCQs and mock tests.';
    let meta = document.querySelector('meta[name="description"]');
    if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.appendChild(meta); }
    meta.setAttribute('content', description);
  }, []);

  return <Layout>
    <section className="hero-wash overflow-hidden text-[hsl(var(--primary-foreground))]">
      <Container className="grid gap-12 py-16 sm:py-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:py-24">
        <div className="rise-in">
          <p className="eyebrow text-[hsl(var(--accent))]">A clear start for your preparation</p>
          <h1 className="font-display mt-4 max-w-2xl text-5xl leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Prepare with <span className="text-[hsl(var(--accent))]">purpose.</span></h1>
          <p className="mt-6 max-w-xl text-base leading-7 text-[hsl(var(--primary-foreground)/.75)] sm:text-lg">Free study material, practice questions and exam-wise guidance for Indian students. Start small, stay consistent.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href="/exams" data-testid="button-hero-browse-exams">Browse exams <ArrowRight size={16} /></Button><Button href="/study-material" variant="secondary" className="border-[hsl(var(--primary-foreground)/.25)] bg-transparent text-[hsl(var(--primary-foreground))] hover:bg-[hsl(var(--primary-foreground)/.1)]" data-testid="button-hero-study-material">Explore study material</Button></div>
        </div>
        <div className="relative mx-auto w-full max-w-[390px] lg:justify-self-end">
          <div className="absolute -right-5 -top-5 h-28 w-28 rounded-full border border-[hsl(var(--accent)/.35)]" /><div className="absolute -bottom-8 -left-8 h-20 w-20 rounded-full bg-[hsl(var(--accent)/.1)]" />
          <Card className="relative overflow-hidden border-[hsl(var(--primary-foreground)/.16)] bg-[hsl(var(--primary-foreground)/.08)] p-6 text-[hsl(var(--primary-foreground))] shadow-none"><div className="flex items-center justify-between border-b border-[hsl(var(--primary-foreground)/.14)] pb-5"><div><p className="text-xs text-[hsl(var(--primary-foreground)/.55)]">Your preparation desk</p><p className="mt-1 font-display text-2xl">One step at a time.</p></div><Target size={26} className="text-[hsl(var(--accent))]" /></div><div className="mt-6 space-y-3"><div className="rounded-lg bg-[hsl(var(--primary-foreground)/.09)] p-4"><div className="flex items-center justify-between text-xs"><span>Understand the concept</span><span className="text-[hsl(var(--accent))]">01</span></div><div className="mt-3 h-1.5 rounded-full bg-[hsl(var(--primary-foreground)/.13)]"><div className="h-full w-[68%] rounded-full bg-[hsl(var(--accent))]" /></div></div><div className="rounded-lg border border-[hsl(var(--primary-foreground)/.14)] p-4 text-sm text-[hsl(var(--primary-foreground)/.7)]"><span className="mr-2 text-[hsl(var(--accent))]">02</span> Practice what you learn</div><div className="rounded-lg border border-[hsl(var(--primary-foreground)/.14)] p-4 text-sm text-[hsl(var(--primary-foreground)/.7)]"><span className="mr-2 text-[hsl(var(--accent))]">03</span> Return stronger tomorrow</div></div></Card>
        </div>
      </Container>
    </section>
    <section className="py-16 sm:py-20"><Container><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><SectionTitle eyebrow="Choose your path" title="Popular exams" description="A simple place to begin. Pick an exam and see what to study next." /><Link href="/exams" className="focus-ring flex w-fit items-center gap-2 rounded px-1 py-2 text-sm font-bold text-[hsl(var(--primary))]" data-testid="link-home-all-exams">View all exams <ArrowRight size={16} /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{exams.map((exam) => <ExamCard key={exam.id} exam={exam} />)}</div></Container></section>
    <section className="paper-grid border-y border-[hsl(var(--border))] py-16 sm:py-20"><Container><SectionTitle eyebrow="What you can use" title="Build a steady study habit." description="Everything here is designed to help you spend less time searching and more time learning." /><div className="mt-10 grid gap-4 md:grid-cols-3"><Card className="p-6"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#f7e3bb] text-[#825413]"><BookOpen size={20} /></span><h3 className="mt-6 text-lg font-bold text-[hsl(var(--primary))]">Study Material</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Find exam-wise notes and subject essentials in one calm workspace.</p><Link href="/study-material" className="focus-ring mt-5 inline-flex items-center gap-2 rounded text-sm font-bold text-[hsl(var(--primary))]" data-testid="link-home-study-material">Explore material <ArrowRight size={15} /></Link></Card><Card className="p-6"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#dce4f2] text-[#34547f]"><Brain size={20} /></span><h3 className="mt-6 text-lg font-bold text-[hsl(var(--primary))]">MCQ Practice</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Keep concepts fresh with question-led practice built for regular revision.</p><Link href="/quiz" className="focus-ring mt-5 inline-flex items-center gap-2 rounded text-sm font-bold text-[hsl(var(--primary))]" data-testid="link-home-quiz">Practice MCQs <ArrowRight size={15} /></Link></Card><Card className="p-6"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#d6ebe5] text-[#246556]"><FileText size={20} /></span><h3 className="mt-6 text-lg font-bold text-[hsl(var(--primary))]">Previous Year Questions</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Use past questions to understand the shape and rhythm of your exam.</p><Link href="/pyq" className="focus-ring mt-5 inline-flex items-center gap-2 rounded text-sm font-bold text-[hsl(var(--primary))]" data-testid="link-home-pyq">See PYQs <ArrowRight size={15} /></Link></Card></div></Container></section>
    <section className="py-16 sm:py-20"><Container className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><SectionTitle eyebrow="A little more depth" title="Theory questions for stronger recall." description="Reading is the first pass. Explaining an idea in your own words is where it stays." /><Button href="/theory" variant="secondary" className="mt-7" data-testid="button-home-theory">Explore theory questions <ArrowRight size={16} /></Button></div><Card className="grid gap-0 overflow-hidden sm:grid-cols-2"><div className="bg-[hsl(var(--primary))] p-7 text-[hsl(var(--primary-foreground))]"><Library size={22} className="text-[hsl(var(--accent))]" /><p className="mt-8 text-xs uppercase tracking-[.15em] text-[hsl(var(--primary-foreground)/.55)]">Try this prompt</p><h3 className="font-display mt-3 text-2xl leading-tight">Explain one idea without looking at your notes.</h3></div><div className="p-7"><p className="text-sm font-bold text-[hsl(var(--primary))]">Good revision feels active.</p><ul className="mt-5 space-y-4 text-sm leading-6 text-[hsl(var(--muted-foreground))]"><li className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[hsl(var(--accent))]" />Write a short answer in your own words.</li><li className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[hsl(var(--accent))]" />Compare it with the key points.</li><li className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[hsl(var(--accent))]" />Return to it after a few days.</li></ul></div></Card></Container></section>
    <section className="bg-[#e9e2d2] py-16 sm:py-20"><Container className="grid gap-8 md:grid-cols-3"><div className="md:col-span-1"><SectionTitle eyebrow="Why ExamSetu4U" title="Less noise. More direction." /></div><div className="grid gap-7 sm:grid-cols-3 md:col-span-2"><div><ShieldCheck size={20} className="text-[hsl(var(--primary))]" /><h3 className="mt-4 font-bold">Free to start</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">A focused foundation without a paywall at the door.</p></div><div><Target size={20} className="text-[hsl(var(--primary))]" /><h3 className="mt-4 font-bold">Exam-wise</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Find relevant material without sorting through everything.</p></div><div><BookOpen size={20} className="text-[hsl(var(--primary))]" /><h3 className="mt-4 font-bold">Made for practice</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Learn, revisit and test your understanding regularly.</p></div></div></Container></section>
    <section className="py-16 sm:py-20"><Container><div className="rounded-xl bg-[hsl(var(--primary))] px-6 py-10 text-center text-[hsl(var(--primary-foreground))] sm:px-10"><p className="eyebrow">Your next session starts here</p><h2 className="font-display mx-auto mt-3 max-w-xl text-3xl leading-tight sm:text-4xl">Make today’s study time count.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[hsl(var(--primary-foreground)/.7)]">Choose an exam, open a topic and take the first useful step.</p><Button href="/exams" className="mt-7" data-testid="button-home-cta">Start with an exam <ArrowRight size={16} /></Button></div></Container></section>
  </Layout>;
}